\context ChordNames
	\chords {
		\set majorSevenSymbol = \markup { "maj7" }
		\set chordChanges = ##t

		% intro
		c2:sus4 c2  | c2:sus4 c2  |

		% sennor, sennor, ten piedad
		c2:sus4 c2  | c2:sus4 c4 e4:m7  |
		a2:m d2  |
		g1  |

		% sennor, sennor, ten piedad
		c2:sus4 c2  | c2:sus4 c4 e4:m7  |
		a2:m d2  |
		g1  |

		% cristo, cristo, ten piedad...
		d2 d2:/cis  |
		b2:m a2  |
		g1  |
		a1  |

		% cristo, cristo, ten piedad...
		d2 d2:/cis  |
		b2:m a2  |
		g1  |
		c1  |
		c1  |

		% sennor, sennor, ten piedad
		c2:sus4 c2  | c2:sus4 c4 e4:m7  |
		a2:m d2  |
		g1  |

		% sennor, sennor, ten piedad
		c2:sus4 c2  | c2:sus4 c4 e4:m7  |
		a2:m d2  |
		g1  |
		a1  |
	}
